# YAML - overall site configuration

# Name of your site (displayed in the header)
name: Bestiario caribeño

# Short bio or description (displayed in the header)
description: Los monstruos del Caribe expuestos a la crítica

locale: es

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://bestiariocaribe.github.io/

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: ""

collections:
  bestiario:
    output: true

#defaults:
#  - scope:
  #    path: ""
   #   type: "bestiario"
   # values:
    #  layout: bestiario

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://pbs.twimg.com/profile_images/1779775150/bitty-icon_bigger.gif

# Jekyll configuration from Zombies reimagined

logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
# locale: en
url: # http://ds.swarthmore.edu/zombies-reimagined
feed:
  path: atom.xml

sass:
  sass_dir: _scss  #changed from _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Site owner
owner: Persephone Braham
#  org: University of Delaware Digital Studies Initiative
  email: braham@udel.edu
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: # logo-mccabe-web.png # 160x160 px image for author byline
  disqus-shortname:

limit_posts: "4"

# Flags below are optional

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: pbraham
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
# disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: 

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: compressed #You might prefer to maxify using :expanded

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
