#
# This file contains configuration flags to customize your site

# Name of site (displayed in the header)
name: Bestiario caribeño

# Short bio or description (displayed in the header)
description: Los monstruos del Caribe expuestos a la crítica

collections:
  bestiario:
    output: true

#defaults:
#  - scope:
  #    path: ""
   #   type: "bestiario"
   # values:
    #  layout: bestiario

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/WhiteZombieAvatar.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: 
  github: pbraham
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
# disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://bestiariocaribe.github.io/

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: compressed #You might prefer to maxify using :expanded
  
  # put in Swat Prose.io template
  # prose.io front matter settings

prose:
  rooturl: '_posts/articles'
  media: 'images'
  metadata:
    _posts/articles:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter your title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "author"
        field:
          element: "hidden"
          value: "group5"
      - name: "group_members"
        field:
          element: "text"
          label: "Group members"
          value: ""
      - name: "modified"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "image_teaser"
        field:
          element: "hidden"
          value: ""
      - name: "storymap_id"
        field:
          element: "text"
          label: "Storymap ID"
          placeholder: "example: 772f6677de9353fe75919801ec1cb48b"
          help: "If including a Storymap, enter the string of characters included in your Storymap project URL"
          value: ""
      - name: "storymap_title"
        field:
          element: "text"
          label: "Storymap title"
          placeholder: "example: los zombis en el caribe"
          help: "If including a Storymap, enter the title associated with your Storymap project"
          value: ""
      - name: "timeline_id"
        field:
          element: "text"
          label: "Timeline ID"
          placeholder: "example: 1uGjhA8mK551YwHW1wRF5sh1utOxDV73JfuJbILe2jOI"
          help: "If including a Timeline, enter the string of characters included in your Timelinejs project URL"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish?"
          help: "Check the box when ready to publish"
value: false

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
